name: CI/CD Pipeline for Next.js

on:
  push:
    branches:
      - main  # Or your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10 # Specify your pnpm version

      - name: Install dependencies
        run: pnpm install 

      - name: Build Next.js app
        run: pnpm run build
        
      - name: Start Next.js app
        run: pnpm run start

     
