name: NextJsPipiline

on:
  push:
    branches: [main]

jobs: 
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - uses: pnpm/action-setup@v3
      with:
        version: 9
    - run: pnpm i
    - run: pnpm run build
